# Generated by Django 5.0 on 2023-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='IMS.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
