# Generated by Django 5.0 on 2023-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_order_products_alter_supplier_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Credit/Debit Card', 'Credit/Debit Card'), ('GCash', 'GCash')], max_length=100, null=True),
        ),
    ]
