# Generated by Django 5.0 on 2023-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0003_remove_order_total_amount_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product_sto',
            field=models.ManyToManyField(to='IMS.product'),
        ),
    ]
