# Generated by Django 5.0 on 2023-12-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_warehouse_capacity_warehouse_product_sto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_number',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IMS.product'),
        ),
    ]
