# Generated by Django 5.0 on 2023-12-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
